# Task 2: Grouped Bar Chart - Average Rating vs Total Reviews for Top 10 App Categories

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from plotly.offline import plot
import plotly.graph_objects as go

In [2]:
# Load the dataset
df = pd.read_csv("Play Store Data.csv")
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [4]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

# Step 1: Data Cleaning & Filtering

In [5]:
# Remove rows with missing values in relevant columns
df = df.dropna(subset=['Category', 'Rating', 'Reviews', 'Installs', 'Size', 'Last Updated'])

In [6]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [7]:

# Clean 'Installs' column
df['Installs'] = df['Installs'].astype(str).str.replace('[+,]', '', regex=True)

# Handle possible missing values before converting to int
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce').fillna(0).astype(int)

In [8]:
# Filter: Rating >= 4.0
df = df[df['Rating'] >= 4.0]

In [9]:
# Convert 'Size' to MB
def convert_size(size):
    if 'M' in size:
        return float(size.replace('M', ''))
    elif 'k' in size:
        return float(size.replace('k', '')) / 1024
    else:
        return np.nan

df['Size_MB'] = df['Size'].replace('Varies with device', np.nan)
df['Size_MB'] = df['Size_MB'].dropna().apply(convert_size)
df = df.dropna(subset=['Size_MB'])

C:\Users\sravy\AppData\Local\Temp\ipykernel_1996\2783219593.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sravy\AppData\Local\Temp\ipykernel_1996\2783219593.py:11: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [10]:
# Filter: Size >= 10 MB
df = df[df['Size_MB'] >= 10]

In [11]:
# Convert 'Last Updated' to datetime
df['Last Updated'] = pd.to_datetime(df['Last Updated'])
df['Update_Month'] = df['Last Updated'].dt.month_name()

In [12]:
# Filter: Only January updates
df = df[df['Update_Month'] == 'January']

## Step 2: Grouping & Aggregation

In [13]:

top_10 = df.groupby('Category')['Installs'].sum().sort_values(ascending=False).head(10).index
df_top = df[df['Category'].isin(top_10)]

grouped = df_top.groupby('Category').agg({'Rating': 'mean', 'Reviews': 'sum'}).reset_index()

In [14]:
# Convert Reviews column to numeric
grouped["Reviews"]=pd.to_numeric(grouped["Reviews"],errors="coerce")

# Normalize Reviews for better visualization
max_reviews = grouped['Reviews'].max()
grouped['Reviews_scaled'] = grouped['Reviews'] / max_reviews * 5  # Scale to match Rating axis
print(max_reviews)

5.984367320376515e+158

## Step 3: Time-Based Plot Visibility

In [18]:
now = datetime.now()
current_hour = now.hour

 ## Step 4: Plot Grouped Bar Chart

In [19]:
if 15 <= current_hour < 17:
    # 📊 Step 4: Plot Grouped Bar Chart
    fig = go.Figure(data=[
        go.Bar(name='Average Rating', x=grouped['Category'], y=grouped['Rating']),
        go.Bar(name='Total Reviews (scaled)', x=grouped['Category'], y=grouped['Reviews_scaled'])
    ])

    fig.update_layout(
        title='Grouped Bar Chart: Avg Rating vs Total Reviews (Top 10 Categories)',
        xaxis_title='App Category',
        yaxis_title='Values',
        barmode='group'
    )
    
# Save as HTML

    fig.write_html("Task2_grouped_bar_chart.html")
    fig.show()
else:
    print(" Chart can only be displayed between 3 PM and 5 PM IST.")

 Chart can only be displayed between 3 PM and 5 PM IST.


**Insights:**

The category with the highest average rating was **PERSONALIZATION**with a rating of **4.47**.

The category with the most total reviews was **FAMILY** with **5.9843** reviews.

This visualization highlights which categories are not only popular but also well-rated by users—providing useful guidance for app developers and marketers to focus on high-engagement and high-satisfaction segments.

**Conclusion:** In this task, we analyzed app categories from the Google Play Store dataset by comparing the total number of Reviews and the average Ratings across each category using a grouped bar chart. This dual comparison allowed us to observe both user engagement (via reviews) and user satisfaction (via ratings) simultaneously.